### ISSUE TITLE
CAN'T LOGIN ADMIN

### ISSUE THREAD

**Issue by excellenz** [zulfizz/ujian-cbt#1]
Dear Mr. Zulfi

That is a great app I think. I am learning and trying to use it. Unfortunately, I cannot use login admin. Can you tell me how to fix it?

Thanks a lot.

**Comment by tank-sys** [comment]
coba bro...
look at cbt.sql or your database, table admin. row Administrator.
change default password '2y$12$b66V3qOxwG44wSaoFLK.g.g4lN2T.g.CnfeHCBuNHWA8x/Sb1xBGS' with this one '$2y$12$EgzAfVa3E6HzfmownYWs0eh2.G0ZylFrnoIj6gt87.F6HnmcdS7aa' dibaca oleh manusia normal "tank-sys".
god luck.
we can not decrypt password_hash php. we only can encrypt and password_verify.

**Comment by jaruki2014** [comment]
Oke
